import "./globals.css";
import { Inter } from "next/font/google";
import { Carousel } from "./carousel.component";
import Link from "next/link";
import { Button } from "@components/button/button.component";
import { SearchIcon } from "@components/icon";
import { Input } from "@components/input/input.component";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const hotNews = [
  {
    id: "1",
    title: "qwerty",
    body: "hello my friend",
    slug: "qwerty",
  },
  {
    id: "2",
    title: "qwerty2",
    body: "hello my friend2",
    slug: "qwerty2",
  },
  {
    id: "3",
    title: "qwerty3",
    body: "hello my friend3",
    slug: "qwerty3",
  },
  {
    id: "4",
    title: "qwerty4",
    body: "hello my friend4",
    slug: "qwerty4",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-emerald-700">
          <div className="bg-blue-500">
            <Link href="/">MAIN</Link>
          </div>
          <Input
            iconLeft={
              <Button color="grey" className="p-1.5">
                HELLo
                <SearchIcon />
              </Button>
            }
          />
        </div>
        {/* <Carousel items={hotNews} withNavigate /> */}

        {children}
      </body>
    </html>
  );
}
